name: Complete CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nix_matrix:
    strategy:
      matrix:
        # 88 is not in nixpkgs anymore
        # 910 does not build yet for unknown reason
        # We are not using nix build .#pyf_all because of github disk limitations
        ghc: [86, 90, 92, 94, 96, 98]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v21
    - uses: cachix/cachix-action@v12
      with:
        name: guibou
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    # Builds cabal (nix)
    - name: Build with GHC ${{ matrix.ghc }}
      run: nix build .#pyf_${{ matrix.ghc }}

  stack_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Stack
      run: sudo apt-get install haskell-stack

    # Build stack
    - name: Stack 9.8
      run: stack --resolver nightly-2024-05-15 test
    - name: Stack 9.6
      run: stack --resolver lts-22.22 test
    - name: Stack 9.4
      run: stack --resolver lts-21.17 test
    - name: Stack 9.2
      run: stack --resolver lts-20.26 test
    - name: Stack 9.0
      run: stack --resolver lts-19.1 test
    - name: Stack 8.10
      run: stack --resolver lts-17.1 test
    - name: Stack 8.8
      run: stack --resolver lts-16.31 test
    - name: Stack 8.6
      run: stack --resolver lts-14.27 test
